### ISSUE TITLE
Make a javadoc

### ISSUE THREAD

**Issue by EricLottman** [roboticsTeam6942v2/2024Offseason#5]
I think itd be helpful idk

**Comment by EricLottman** [comment]
Or alternatively a wiki? or both

**Comment by jdon578** [comment]
javadoc would be easy to do since it would just take adding comments into the code itself and generating the html, ive used it for my classes so im used to using it if you want me to go in and work on that

**Comment by EricLottman** [comment]
Bet, I have no clue how it works, but if its really that easy then go for it
